### create user
post http://localhost:3000/user
Content-Type: application/json

{
    "name":"khang",
    "email":"ngk.khang94@gmail.com",
    "password": "khang2901"
}

###get all user
Get http://localhost:3000/user

###login
post http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"ngk.khang94@gmail.com",
    "password": "khang29012"
}